image: docker.digi-texx.vn/u-builder:node18.12.1-3
variables:
  IMAGE: $CI_COMMIT_TAG
  NAME_LIB: grids
stages:
  - build
build_image:
  stage: build
  script:
    - mkdir -p /usr/dgu/libs/$NAME_LIB
    - cp -R . /usr/dgu/libs/$NAME_LIB
    - cd /usr/dgu
    - /bin/sh ./publish.sh $NAME_LIB $NPM_TOKEN
  only:
    - tags
